version: '3.8'

services:
  landcomp-app:
    image: ghcr.io/blockrunner/landcomp-app:latest
    container_name: landcomp-app
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/var/log/nginx
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - landcomp-network

networks:
  landcomp-network:
    driver: bridge

volumes:
  logs:
