name: iOS Build & Test

on:
  push:
    branches: [ main, develop ]

jobs:
  ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Setup iOS
        run: |
          cd ios
          pod install
      
      - name: Run code analysis
        run: flutter analyze
      
      - name: Check code formatting
        run: dart format --set-exit-if-changed .
      
      - name: Run tests
        run: flutter test --coverage
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info
          flags: ios
          name: ios-coverage
      
      - name: Build iOS (Simulator)
        run: flutter build ios --simulator
      
      - name: Build iOS (Release - No Codesign)
        if: github.ref == 'refs/heads/main'
        run: flutter build ios --release --no-codesign
      
      - name: Upload iOS artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/Runner.app
