name: Web Build & Deploy

on:
  push:
    branches: [ main, develop ]

jobs:
  web:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true
      
      - name: Enable web
        run: flutter config --enable-web
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Run code analysis
        run: flutter analyze
      
      - name: Check code formatting
        run: dart format --set-exit-if-changed .
      
      - name: Run tests
        run: flutter test --coverage
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info
          flags: web
          name: web-coverage
      
      - name: Build Web (Debug)
        run: flutter build web --debug
      
      - name: Build Web (Release)
        if: github.ref == 'refs/heads/main'
        run: flutter build web --release
      
      - name: Upload Web artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/
      
      - name: Deploy to Firebase Hosting
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: landscape-ai-app
